Feature/rating
wecode-bootcamp-korea/13-watchandchill-frontend pull request #5
Opened 2020-10-27 13:23 UTC by beginal

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항들 자세한 내용
- Rating Page 750px 이하일 경우 반응형 추가
- Analysis Page 750px 이하 반응형 추가
- People Page 추가
(이미 머지된 파일들이 있어서  실수로 한개의 브랜치에 다 합친 후 작업해버려서 그대로 한개에서 작업 진행했습니다..)
- 다른 브랜치들과 합치면서 발생한 Conflict 해결

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-28 05:56 UTC, Jun4928 requested changes
리뷰 확인 및 반영해주세요

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Analysis/MovieInfos.js
>    btnRef = createRef();
1. supervisors 안에 들어가는 데이터가 constructor() 생성자 안에서 하드코딩 되어있네요. 
한 번 선언되고 바뀔값이 아니라면 상태로 관리하는것이 의미가 없습니다. 
상수로 클래스 밖에서 선언해서 사용하거나, 데이터베이스에서 오는 데이터라면 목데이터 생성 후 fetch 로 불러와서 사용해 주세요

2. `liLength` 와 `btnRef` 가 constructor() 생성자 밖에서 선언되어 있네요. 
자바스크립트의 최신 문법에 [제안사항](https://github.com/tc39/proposal-class-fields) 으로 추가되어 보이는데 클래스 내부에서 사용될 field 값들은 그냥 constructor() 에서 생성해 주세요.

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Contents.js
> +    }
스크롤 내릴 때 Nav 바를 투명하게 하려고 컴포넌트 자체의 className 에 접근해서 스타일링을 하고 있네요.
즉, DOM 객체에 직접접근 하고 있습니다. 안티패턴 입니다. 

Routes.js 보니까 Analysis, Rating 컴포넌트가 상태를 props로 내려받고 있습니다. 

이 컴포넌트도 Routes.js 에서 상태를 핸들링 하는 함수를 props로 내려받고, 
이벤트에 따라 상태를 바꾸어서, 형제관계에 있는 Nav 컴포넌트가 상태를 props로 받아서 
className 을 변경하도록 하는 방법은 어떨까요?

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Analysis/MovieInfos.js
> +  componentDidMount() {
메소드 사이에 빈 줄 넣어주세요

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Contents.js
> +        <body>
body 태그를 여기에 사용하신 이유가 뭔가요?
**index.html** 에 보면 아래와 같이 태그가 작성되어있는데,
Contents.js 컴포넌트 안에 body 태그가 있는게 올바른 방법일까요?
```html
<head>
</head>
<body>
  <div id="root"></div>
</body>
```

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Contents.js
> +              movieInfo.cast.map(actor => <ActorProfile actorInfo={actor} />)}
같은 컴포넌트가 map 함수로 배열에 담기면 key 값이 필수적으로 있어야 합니다.

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Contents.js
> +              movieInfo.cast.map(actor => <ActorProfile actorInfo={actor} />)}
빠트린 곳이 있으면 모두 다 수정해주세요!

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Contents.scss
> +    outline: none;
새로운 className 때문에 중괄호가 열리는 곳에서는 
띄어쓰기로 로직을 분리해주세요.

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/Contents/Info/Info.scss
> +article {
이 파일도 빈 줄이 없네요.
가독성 고려해 주세요!

2020-10-28 05:56 UTC, Jun4928 commented on src/pages/People/People.js
> +          {films.map(({title, poster}) =>
map 콜백함수 첫번째 인자 구조분해할당 Good!

2020-10-28 08:05 UTC, beginal commented on src/pages/Contents/Contents.scss
> +    outline: none;
Contents 폴더 내부는 slick과 modal을 제외하고 모두 지안님이 하신부분입니다! 지안님과 제 코드가 머지 된 후  pull받아서 다시 작업하느라 합쳐졌습니다!! 수정사항 전달할게요~!

2020-10-28 08:22 UTC, beginal commented on src/pages/Analysis/MovieInfos.js
>    btnRef = createRef();
수정했습니다!

2020-10-29 01:49 UTC, jian7061 commented on src/pages/Contents/Contents.js
> +        <body>
수정했습니다!

2020-10-29 01:59 UTC, jian7061 commented on src/pages/Contents/Contents.js
> +              movieInfo.cast.map(actor => <ActorProfile actorInfo={actor} />)}
수정했습니다!

2020-10-29 02:18 UTC, jian7061 commented on src/pages/Contents/Contents.scss
> +    outline: none;
수정했습니다!

2020-10-29 02:21 UTC, jian7061 commented on src/pages/Contents/Info/Info.scss
> +article {
수정했습니다!

2020-10-29 04:43 UTC, merged